//! # &inator Constraint Generation
//!
//! In this module, we generate SMT constraints based on a LabLLVM program and
//! the results of static analyses on it.

pub mod borrowing;
pub mod consistency;
pub mod context;
pub mod datatypes;
pub mod functions;
pub mod lifetimes;
pub mod loans;
pub mod optimality;
pub mod relations;
pub mod semantic;

use std::collections::BTreeMap;

use z3::ast::{Bool, Int};

use crate::{
    constraints::{
        context::{Context, ContextKey},
        functions::{SingletonFunction, labrtype::LabRType},
    },
    lang::{function::FuncIdent, program::Program},
};

/// The kinds of constraints that appear in a `ConstraintSystem`.
#[derive(PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ConstraintKind {
    Axioms,
    CParity,
    CArray,
    CSlice,
    CStruct,
    CStructRecursive,
    CEquiv,
    CPtrTransform,
    CImmutable,
    CMutable,
    SPtrOwning,
    SPtrTransform,
    SStructClonable,
    SClone,
    SReferent,
    SAlias,
    LLiveness,
    LSubtype,
    LInvariant,
    LReborrow,
    LParam,
    LHom,
    LMerge,
    LTransfer,
    BBorrow,
    BAssign,
    BMove,
    BDrop,
    Debug,
}

impl ConstraintKind {
    /// Gets the names of the inference rules used to generate this kind of
    /// constraint.
    pub fn rule_names(&self) -> &'static [&'static str] {
        match self {
            Self::Axioms => &["Axioms"],
            Self::CParity => &["C-Parity-*"],
            Self::CArray => &["C-Array-*"],
            Self::CSlice => &["C-Slice"],
            Self::CStruct => &["C-LifeParam-*", "C-Struct"],
            Self::CStructRecursive => &["C-Rank"],
            Self::CEquiv => &["C-Equiv-*"],
            Self::CPtrTransform => &["C-Transform-*"],
            Self::CImmutable => &["C-Immut-*"],
            Self::CMutable => &["C-Mut"],
            Self::SPtrOwning => &["S-Owning-*"],
            Self::SPtrTransform => &["S-Transform-*"],
            Self::SStructClonable => &["S-Clonable"],
            Self::SClone => &["S-Clone-*"],
            Self::SReferent => &["S-Referent-*"],
            Self::SAlias => &["S-Alias-*"],
            Self::LLiveness => &["L-Liveness"],
            Self::LSubtype => &["L-Subtype-*"],
            Self::LInvariant => &["L-Invariant-*"],
            Self::LReborrow => &["L-Reborrow-*"],
            Self::LParam => &["L-Param"],
            Self::LHom => &["L-Hom"],
            Self::LMerge => &["L-Merge"],
            Self::LTransfer => &["L-Transfer"],
            Self::BBorrow => &["B-Borrow"],
            Self::BAssign => &["B-Assign"],
            Self::BMove => &["B-Move"],
            Self::BDrop => &["B-Drop"],
            Self::Debug => &["DEBUG"],
        }
    }
}

/// The kinds of objectives that appear in a `ConstraintSystem`.
#[derive(PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum ObjectiveKind {
    SignatureTypeArrayCount,
    SignatureTypeCellCount,
    SignatureTypeTransform,
    SignatureTypeDynamicOverhead,
}

impl ObjectiveKind {
    /// Gets the name of the inference rules used to generate this kind of
    /// objective.
    pub fn rule_name(&self) -> &'static str {
        match self {
            Self::SignatureTypeArrayCount => "P-Array",
            Self::SignatureTypeCellCount => "P-Cell",
            Self::SignatureTypeTransform => "P-Transform",
            Self::SignatureTypeDynamicOverhead => "P-Overhead",
        }
    }
}

/// The constraint system generated by &inator for a program.
pub struct ConstraintSystem<'a> {
    pub program: &'a Program<'a>,
    pub ctx: Context<'a>,
    pub constraints: BTreeMap<ConstraintKind, Vec<Bool>>,
    pub objectives: Vec<(ObjectiveKind, Int)>,
}

impl<'a> ConstraintSystem<'a> {
    fn gen_debug(_ctx: &Context, _program: &Program) -> Vec<Bool> {
        #[allow(unused_mut)]
        let mut assertions = vec![];

        // TypeLab lists known to be pointers to strings.
        let mut known_str_typelabs = vec![];

        if let Some(func) = _program.try_get_function(&FuncIdent(String::from("printf"))) {
            known_str_typelabs.push(&_program.get_local(&func.param_vars[0]).typelabs);
        }
        if let Some(func) = _program.try_get_function(&FuncIdent(String::from("fprintf"))) {
            known_str_typelabs.push(&_program.get_local(&func.param_vars[1]).typelabs);
        }
        if let Some(func) = _program.try_get_function(&FuncIdent(String::from("puts"))) {
            known_str_typelabs.push(&_program.get_local(&func.param_vars[0]).typelabs);
        }
        if let Some(func) = _program.try_get_function(&FuncIdent(String::from("fputs"))) {
            known_str_typelabs.push(&_program.get_local(&func.param_vars[0]).typelabs);
        }
        if let Some(func) = _program.try_get_function(&FuncIdent(String::from("strlen"))) {
            known_str_typelabs.push(&_program.get_local(&func.param_vars[0]).typelabs);
        }
        if let Some(func) = _program.try_get_function(&FuncIdent(String::from("strcmp"))) {
            known_str_typelabs.push(&_program.get_local(&func.param_vars[0]).typelabs);
            known_str_typelabs.push(&_program.get_local(&func.param_vars[1]).typelabs);
        }

        for typelabs in known_str_typelabs {
            assertions.push(LabRType::apply(_ctx, &(typelabs[0].into(),)).is_shared(_ctx));
        }

        for func in _program.functions() {
            // `memcpy` and `memmove` intrinsics
            if func.id.0.find("llvm.memcpy.") == Some(0)
                || func.id.0.find("llvm.memmove.") == Some(0)
                || func.id.0.find("__memcpy_chk") == Some(0)
            {
                let dst_frag = LabRType::apply(
                    _ctx,
                    &(_program.get_local(&func.param_vars[0]).typelabs[0].into(),),
                );
                let src_frag = LabRType::apply(
                    _ctx,
                    &(_program.get_local(&func.param_vars[1]).typelabs[0].into(),),
                );
                assertions.push(dst_frag.is_mut(_ctx));
                assertions.push(src_frag.is_shared(_ctx));
            }

            // `memset` intrinsic
            if func.id.0.find("llvm.memset.") == Some(0) {
                let dst_frag = LabRType::apply(
                    _ctx,
                    &(_program.get_local(&func.param_vars[0]).typelabs[0].into(),),
                );
                assertions.push(dst_frag.is_mut(_ctx));
            }
        }

        assertions
    }

    /// Construct the constraint system for LabLLVM program `program`.
    pub fn construct(program: &'a Program<'a>) -> ConstraintSystem<'a> {
        let mut ctx = Context::new(program);

        let axioms = std::mem::take(&mut ctx.axioms);

        let ctx = ctx;

        let c_parity = consistency::gen_parity(&ctx, program);
        let c_array = consistency::gen_array(&ctx);
        let c_slice = consistency::gen_slice(&ctx, program);
        let c_struct = consistency::gen_struct(&ctx, program);
        let c_struct_rec = consistency::gen_struct_rec(&ctx, program);
        let c_equiv = consistency::gen_equiv(&ctx, program);
        let c_transform = consistency::gen_transform(&ctx, program);
        let c_immut = consistency::gen_immutable(&ctx, program);
        let c_mut = consistency::gen_mutable(&ctx, program);

        let s_owning = semantic::gen_owning(&ctx, program);
        let s_transform = semantic::gen_transform(&ctx, program);
        let s_clonable = semantic::gen_struct_clonable(&ctx, program);
        let s_referent = semantic::gen_referent(&ctx, program);

        let l_liveness = lifetimes::gen_liveness(&ctx, program);
        let l_subtype = lifetimes::gen_subtyping(&ctx, program);
        let l_invariant = lifetimes::gen_invariance(&ctx, program);
        let l_reborrow = lifetimes::gen_reborrowing(&ctx, program);
        let l_param = lifetimes::gen_parameters(&ctx, program);
        let l_hom = lifetimes::gen_homomorphic(&ctx, program);

        let l_merge = loans::gen_merge(&ctx);
        let l_transfer = loans::gen_transfer(&ctx, program);

        let borrow_conflicts = borrowing::find_borrow_conflicts(&ctx);
        let assign_conflicts = borrowing::find_assign_conflicts(&ctx, program);

        let b_borrow = borrowing::gen_borrow(&ctx, &borrow_conflicts);
        let b_assign = borrowing::gen_assign(&ctx, program, &assign_conflicts);
        let b_move = borrowing::gen_move(&ctx, program, &borrow_conflicts);
        let b_drop = borrowing::gen_drop(&ctx, program);

        let c_debug = Self::gen_debug(&ctx, program);

        let mut constraints = BTreeMap::new();

        constraints.insert(ConstraintKind::Axioms, axioms);

        constraints.insert(ConstraintKind::CParity, c_parity);
        constraints.insert(ConstraintKind::CArray, c_array);
        constraints.insert(ConstraintKind::CSlice, c_slice);
        constraints.insert(ConstraintKind::CStruct, c_struct);
        constraints.insert(ConstraintKind::CStructRecursive, c_struct_rec);
        constraints.insert(ConstraintKind::CEquiv, c_equiv);
        constraints.insert(ConstraintKind::CPtrTransform, c_transform);
        constraints.insert(ConstraintKind::CImmutable, c_immut);
        constraints.insert(ConstraintKind::CMutable, c_mut);

        constraints.insert(ConstraintKind::SPtrOwning, s_owning);
        constraints.insert(ConstraintKind::SPtrTransform, s_transform);
        constraints.insert(ConstraintKind::SStructClonable, s_clonable);
        constraints.insert(ConstraintKind::SReferent, s_referent);

        constraints.insert(ConstraintKind::LLiveness, l_liveness);
        constraints.insert(ConstraintKind::LSubtype, l_subtype);
        constraints.insert(ConstraintKind::LInvariant, l_invariant);
        constraints.insert(ConstraintKind::LReborrow, l_reborrow);
        constraints.insert(ConstraintKind::LParam, l_param);
        constraints.insert(ConstraintKind::LHom, l_hom);

        constraints.insert(ConstraintKind::LMerge, l_merge);
        constraints.insert(ConstraintKind::LTransfer, l_transfer);

        constraints.insert(ConstraintKind::BBorrow, b_borrow);
        constraints.insert(ConstraintKind::BAssign, b_assign);
        constraints.insert(ConstraintKind::BMove, b_move);
        constraints.insert(ConstraintKind::BDrop, b_drop);

        constraints.insert(ConstraintKind::Debug, c_debug);

        let p_cell = optimality::gen_cell_sig(&ctx, program);
        let p_transform = optimality::gen_base_transform_sig(&ctx, program);
        let p_overhead = optimality::gen_base_overhead_sig(&ctx, program);
        let p_array = optimality::gen_array_sig(&ctx, program);

        let objectives = vec![
            (ObjectiveKind::SignatureTypeCellCount, p_cell),
            (ObjectiveKind::SignatureTypeTransform, p_transform),
            (ObjectiveKind::SignatureTypeDynamicOverhead, p_overhead),
            (ObjectiveKind::SignatureTypeArrayCount, p_array),
        ];

        Self {
            program,
            ctx,
            constraints,
            objectives,
        }
    }
}
